### ISSUE TITLE
Assignment #6 Question 4

### ISSUE THREAD

**Issue by awwalker** [mmcky/nyu-econ-370#15]
In Assignment #6 Question 4 we are asked about returns and tasked with showing that:
![screen shot 2016-05-01 at 9 55 14 pm](https://cloud.githubusercontent.com/assets/11507633/14945870/681f6728-0fe7-11e6-840a-585e70dfac1f.png)

Mathematically though isn't that asking to prove equality between a vector or scalar on the left and a matrix on the right? Any help would be appreciated...

**Comment by subhankar94** [comment]
Agreed, help would be appreciated. What exactly do E_t(R_t+1) and cov_t(m_t+1, R_t+1)  mean?

**Comment by mmcky** [comment]
@awwalker @subhankar94. Please submit what you have done for the homework. We will release full solutions to all questions in the next day or so.

**Comment by mmcky** [comment]
Also - think deeply about what **R** represents and how to correctly compute the **Expected Value**. 
The trick is in computing **E(R)**.
