### ISSUE TITLE
Assignment Submissions

### ISSUE THREAD

**Issue by subhankar94** [mmcky/nyu-econ-370#7]
Hi, is there a course staff mailing list where we would send our assignments? If not, which emails ID(s) would you prefer we sent the assignments to?

**Comment by mmcky** [comment]
My email address is: `mm8390@nyu.edu` and is on the front of each set of Lecture notes.

**Comment by subhankar94** [comment]
Great! And just to your ID then?

**Comment by mmcky** [comment]
For the programming assignments - just to my email is fine.
