### ISSUE TITLE
Inputs listed as "In[*]", suddenly unable to generate output in notebook

### ISSUE THREAD

**Issue by ghost** [mmcky/nyu-econ-370#8]
I'm working through the intro to Python 2 notebook. All of a sudden I'm seeing "In[*]" whenever I run a line. 
No output is produced either. 

When I run the same code in a new notebook, it works. What is happening here?
![screen shot 2016-02-14 at 12 15 54 am](https://cloud.githubusercontent.com/assets/16931437/13031995/6d57a800-d2b0-11e5-97be-55b4cee6278f.png)

**Comment by RC18** [comment]
should've attached this too. the notebook with the issue: 
![screen shot 2016-02-14 at 12 15 54 am](https://cloud.githubusercontent.com/assets/16931437/13031991/3c1adef6-d2b0-11e5-8935-f2453583cb32.png)

**Comment by mmcky** [comment]
Sometimes the "[*]" means that python is waiting for some action to be performed. For example if you have a pyplot window open behind the browser (rather than using inline plots through the ipython magics) then python will wait until you close that window and execution continues.

**Comment by ghost** [comment]
I didn't have anything open but what worked for me was going to Kernel > interrupt and running the code again. Thanks!
